---
abstract: 'Data provider or the OpenMusem museum management'
author:
  - 'Samuel W. Flint <linuxkid@linux.com>'
build_requires:
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.6302, CPAN::Meta::Converter version 2.120921'
license: gpl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: OpenMuseum
no_index:
  directory:
    - t
    - inc
requires:
  DBD::mysql: 4.022
  DBI: 1
  perl: 5.006
version: 0.80
